# Generated by Django 4.0.1 on 2022-03-31 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0009_alter_progressreport_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressreport',
            name='subject',
        ),
    ]
