# Generated by Django 4.0.1 on 2022-03-31 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_remove_progressreport_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base_app.subject'),
        ),
    ]
