# Generated by Django 4.0.1 on 2022-03-31 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_progressreport_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progressreport',
            old_name='subjects',
            new_name='subject',
        ),
    ]
